### ISSUE TITLE
Suggestion: Prefer ActionResult<T> instead of IActionResult in Controllers

### ISSUE THREAD

**Issue by awright18** [cbehrends/DotNetCoreCleanArchitectureSample#1]
ActionResult<T> will remove the need for Produces attribute for the return type. 
[Action Result of T and Produces](https://joonasw.net/view/aspnet-core-2-1-actionresult-of-t)

**Comment by cbehrends** [comment]
Agreed, this is a much cleaner way to handle this bit.
