### ISSUE TITLE
Suggestion: Use Default Api Convetions 

### ISSUE THREAD

**Issue by awright18** [cbehrends/DotNetCoreCleanArchitectureSample#2]
if you add [assembly: ApiConventionType(typeof(DefaultApiConventions))] to decorate your startup class this will handle the other Produces for http status codes based on the [default api conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2).

```
[assembly: ApiConventionType(typeof(DefaultApiConventions))]
namespace ApiConventions
{
    public class Startup
    {
```

**Comment by cbehrends** [comment]
Point taken, I forget this exists.  Old habits can die hard :)
